spring:
  application:
    name: schoolapi
  datasource:
    # The jdbc url is: jdbc:h2:mem:schoolapidb
    url: jdbc:h2:mem:schoolapidb;DB_CLOSE_DELAY=-1 # for In-memory database and jdbc:h2:file:[path/database-name] for disk-based database.
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
  h2:
    console:
      enabled: true # The console url is: /h2-console
  sql:
    init:
      data-locations: classpath:db-init/data.sql
      mode: always

server:
  servlet:
    context-path: /api/v1

jwt:
  secret: GD8kDfkhiDN10S5Nc8enVtjAcd8aLJV0Oc0t964ZhBx10K7y # To have environment variable for your secret
  expiration: 3600000 # 1 hour

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
